name = "java-quiz-app"
compatibility_date = "2024-04-05"
pages_build_output_dir = "./dist" # This is required for production builds

[[d1_databases]]
binding = "DB"
database_name = "quiz-db"
database_id = "b54a3ca0-2810-4113-9628-42e9acf03970"
migrations_dir = "./migrations" # Add this line


[dev]
port = 8789 # Use a different port for local development

[[services]]
binding = "AI_PROXY_SERVICE"
service = "47.99.123.168:3001"
